quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=oop_user
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/oop2_db

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true