quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=oop_user
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/oop2_db
quarkus.datasource.devservices.enabled=false

quarkus.http.port=8081

quarkus.oidc.auth-server-url=http://localhost:8080/realms/oop3
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=p6aqQTmCRv42ypH17Ac5SpBVzK8xliiA
quarkus.oidc.application-type=service
quarkus.oidc.discovery-enabled=true
quarkus.oidc.jwks-path=/protocol/openid-connect/certs
quarkus.oidc.token.allow-jwt-introspection=false